[package]
name = "nature_integrate_test_converter"
version = "0.0.3"
authors = ["XueBin Li <llxxbb@yeah.net>"]
edition = "2018"
workspace = "../Nature"

description = "Local converters used by Nature Test"
repository = "https://github.com/llxxbb/Nature-Integrate-test-converter"
license = "MIT"


[dependencies]
nature_common = {path = "../Nature-Common", version="0.0.3"}

[lib]
crate-type = ["cdylib"]