[package]
name = "nature_integrate_test_converter"
version = "0.1.0"
authors = ["xuebin.Li <llxxbb@yeah.net>"]

[dependencies]
nature_common = {path = "../Nature-Common"}
[lib]
crate-type = ["dylib","rlib"]